pipeline {
    agent none
    environment {
       PATH = "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/ankeshkatiyar/Downloads/apache-maven-3.5.4/bin"
   }
    stages {
        stage('Build') {
          agent {
          docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
                }
              }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
